name: New site
description: Request a manga site Mangette does not have yet
title: "[Site]: "
labels: ["New Connector"]
body:
  - type: input
    attributes:
      label: Website-Link
      placeholder: https://
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        If you want to implement this, read [Contributing](https://github.com/TopHatMan/mangette/blob/main/CONTRIBUTING.md). Thank you!